// Rutas de senderismo en Cantabria aptas para ir con peques.
// km, desnivel y tipo son ORIENTATIVOS; el dato exacto está en el track de Wikiloc.
// `wikiloc`: enlace directo al track (resuelto uno a uno). Si falta, se usa búsqueda en Google.

export const routes = [
  { name: "Bosque de Secuoyas de Cabezón de la Sal", comarca: "Saja-Nansa", zona: "Monte Cabezón", km: 1.5, desnivel: 30, tipo: "Circular", resumen: "Bosque mágico de secuoyas gigantes, casi llano, 30–40 min. Perfecto para los más peques.", wikiloc: "https://www.wikiloc.com/hiking-trails/bosque-de-secuoyas-monte-de-cabezon-de-la-sal-72381719" },
  { name: "Dunas de Liencres", comarca: "Santander", zona: "Liencres", km: 3, desnivel: 40, tipo: "Circular", resumen: "Pinar y dunas junto al mar con senderos cortos y planos. Termina en playa.", wikiloc: "https://www.wikiloc.com/hiking-trails/dunas-de-liencres-circular-53267738" },
  { name: "Faro de Cabo Mayor", comarca: "Santander", zona: "Santander", km: 2, desnivel: 20, tipo: "Lineal", resumen: "Paseo costero asfaltado con grandes vistas al mar. Apto para carrito.", wikiloc: "https://www.wikiloc.com/walking-trails/faro-cabo-mayor-playa-bocal-santander-18588293" },
  { name: "Nacimiento del Río Asón", comarca: "Asón-Agüera", zona: "Soba", km: 1, desnivel: 50, tipo: "Lineal", resumen: "Cascada espectacular ('cola de caballo'); mirador a pocos minutos del aparcamiento.", wikiloc: "https://www.wikiloc.com/hiking-trails/ason-cascada-del-ason-ason-9143605" },
  { name: "Ría de San Vicente de la Barquera", comarca: "Costa Occidental", zona: "San Vicente", km: 4, desnivel: 20, tipo: "Lineal", resumen: "Paseo llano junto a la ría con vistas a los Picos de Europa.", wikiloc: "https://www.wikiloc.com/walking-trails/san-vicente-de-la-barquera-castillo-del-rey-39571114" },
  { name: "Molinos del Río Aguanaz", comarca: "Trasmiera", zona: "Entrambasaguas", km: 3, desnivel: 40, tipo: "Circular", resumen: "Sendero fácil junto al río y su manantial, con sombra y agua todo el camino.", wikiloc: "https://www.wikiloc.com/hiking-trails/surgencia-del-rio-aguanaz-y-barrios-de-entrambasaguas-93263515" },
  { name: "Fuente Dé y praderas de Áliva", comarca: "Liébana", zona: "Picos de Europa", km: 6, desnivel: 150, tipo: "Lineal", resumen: "Teleférico + paseos suaves arriba; alta montaña sin apenas esfuerzo.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/fuente-de-refugio-aliva-por-chalet-real-26488136" },
  { name: "Pozo Tremeo y Saja", comarca: "Besaya", zona: "Rumoroso", km: 5, desnivel: 120, tipo: "Circular", resumen: "Bosque de robles y hayas, sendero tranquilo y umbrío junto a un pozo natural.", wikiloc: "https://www.wikiloc.com/hiking-trails/senda-del-pozo-tremeo-59264833" },
  { name: "Playa y senda de Oyambre", comarca: "Costa Occidental", zona: "Comillas", km: 4, desnivel: 30, tipo: "Lineal", resumen: "Praderas costeras llanas, dunas y vistas al mar abierto.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/playa-de-oyambre-desde-comillas-38108416" },
  { name: "Cabárceno (senderos del parque)", comarca: "Trasmiera", zona: "Penagos", km: 5, desnivel: 100, tipo: "Circular", resumen: "Animales en semilibertad + caminos asfaltados; jornada redonda con peques.", wikiloc: "https://www.wikiloc.com/walking-trails/parque-natural-de-cabarceno-137327336" },
  { name: "Mirador de Santa Catalina (Soplao)", comarca: "Saja-Nansa", zona: "Rionansa", km: 1, desnivel: 40, tipo: "Lineal", resumen: "Paseo corto al mirador y al entorno de la cueva de El Soplao." },
  { name: "Embalse del Ebro (presa y orillas)", comarca: "Campoo", zona: "Campoo", km: 5, desnivel: 50, tipo: "Circular", resumen: "Orillas del embalse en terreno llano y abierto, ideal para corretear.", wikiloc: "https://www.wikiloc.com/hiking-trails/circular-en-la-presa-del-embalse-del-ebro-4592096" },
  { name: "Las Tetas de Liérganes (Marimón)", comarca: "Trasmiera", zona: "Liérganes", km: 5, desnivel: 250, tipo: "Circular", resumen: "Subida corta pero con chispa a los dos picos gemelos; miradores sobre Liérganes.", wikiloc: "https://www.wikiloc.com/hiking-trails/a-las-tetas-de-lierganes-circular-50106032" },
  { name: "Cascada del Bolao (Cóbreces)", comarca: "Costa Occidental", zona: "Alfoz de Lloredo", km: 1, desnivel: 30, tipo: "Lineal", resumen: "Cascada que cae directa al mar; paseo muy corto desde el coche.", wikiloc: "https://www.wikiloc.com/hiking-trails/cascada-molino-el-bolao-desde-cobreces-cantabria-6758347" },
  { name: "Sendero del Río Gándara", comarca: "Asón-Agüera", zona: "Soba", km: 5, desnivel: 100, tipo: "Lineal", resumen: "Ruta junto al río con pozas, fácil y refrescante en verano.", wikiloc: "https://www.wikiloc.com/walking-trails/ruta-circular-por-el-rio-gandara-la-gandara-cantabria-57071849" },
  { name: "Marismas de Santoña (observatorio)", comarca: "Trasmiera", zona: "Santoña", km: 3, desnivel: 10, tipo: "Lineal", resumen: "Pasarelas llanas para ver aves; ideal con prismáticos. Apto carrito.", wikiloc: "https://www.wikiloc.com/hiking-trails/paseo-por-la-marisma-de-santona-9467872" },
  { name: "Monte Buciero – Faro del Caballo", comarca: "Trasmiera", zona: "Santoña", km: 6, desnivel: 250, tipo: "Lineal", resumen: "Versión corta hasta los miradores (las 700 escaleras finales son opcionales).", wikiloc: "https://www.wikiloc.com/hiking-trails/monte-buciero-y-faro-del-caballo-12298902" },
  { name: "Costa Quebrada – Urros de Liencres", comarca: "Santander", zona: "Piélagos", km: 4, desnivel: 60, tipo: "Circular", resumen: "Acantilados y formaciones rocosas espectaculares, sendas cortas señalizadas.", wikiloc: "https://www.wikiloc.com/walking-trails/urros-de-liencres-paseo-por-los-acantilados-de-la-costa-quebrada-desde-la-playa-de-portio-a-la-play-85488535" },
  { name: "Playa de Langre y su mirador", comarca: "Trasmiera", zona: "Ribamontán al Mar", km: 2, desnivel: 30, tipo: "Lineal", resumen: "Paseo por lo alto del acantilado, vistas y bajada a arena dorada.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/mirador-langre-y-playa-de-langre-desde-langre-161861693" },
  { name: "Lagos de la zona de Brañavieja", comarca: "Campoo", zona: "Alto Campoo", km: 4, desnivel: 150, tipo: "Circular", resumen: "Entorno de montaña suave, praderas y aire puro de altura.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/branavieja-los-habitats-de-alto-campoo-83084172" },
  { name: "Bárcena Mayor (pueblo y río)", comarca: "Saja-Nansa", zona: "Los Tojos", km: 4, desnivel: 80, tipo: "Circular", resumen: "Uno de los pueblos más bonitos de España + paseo llano junto al río Argoza.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/barcena-mayor-con-ninos-15924964" },
  { name: "Sendero de los Molinos de Liérganes", comarca: "Trasmiera", zona: "Liérganes", km: 5, desnivel: 100, tipo: "Circular", resumen: "Ruta circular fácil entre prados, río y casonas montañesas.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/senda-de-los-molinos-circular-51025463" },
  { name: "Cueva de El Pendo (entorno)", comarca: "Santander", zona: "Escobedo", km: 2, desnivel: 50, tipo: "Lineal", resumen: "Paseo corto a una cueva con arte rupestre Patrimonio de la Humanidad.", wikiloc: "https://www.wikiloc.com/hiking-trails/cueva-del-pendo-ermita-san-pantaleon-59890122" },
  { name: "Mirador de la Cardosa", comarca: "Saja-Nansa", zona: "Saja-Nansa", km: 1, desnivel: 30, tipo: "Lineal", resumen: "Acceso fácil a un balcón con vistas sobre los valles del Nansa.", wikiloc: "https://www.wikiloc.com/hiking-trails/puerto-de-la-palombera-balcon-de-la-cardosa-6910525" },
  { name: "Senda fluvial del río Pisueña", comarca: "Valles Pasiegos", zona: "Castañeda", km: 5, desnivel: 30, tipo: "Lineal", resumen: "Llana junto al río, con tirolina y parque infantil cubierto por el camino.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/senda-fluvial-pisuena-23661523" },
  { name: "Paseo Fluvial de las Escubias de Barcenaciones", comarca: "Besaya", zona: "Reocín", km: 3, desnivel: 20, tipo: "Circular", resumen: "Llana junto al Saja, con casonas y figuras mitológicas ('Territorio Escubías').", wikiloc: "https://www.wikiloc.com/hiking-trails/paseo-por-barcenaciones-91621294" },
  { name: "Calzada Romana del Monte Fresneda", comarca: "Besaya", zona: "Los Corrales de Buelna", km: 6, desnivel: 200, tipo: "Circular", resumen: "Recorrido histórico por una calzada romana oculta entre bosque.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/calzada-del-monte-fresneda-17902877" },
  { name: "El Castillo de Montehano", comarca: "Trasmiera", zona: "Escalante", km: 4, desnivel: 120, tipo: "Circular", resumen: "Pequeña cumbre entre marismas con ruinas de castillo y convento.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/escalante-castillo-de-montehano-92974451" },
  { name: "Senda Fluvial del Río Besaya", comarca: "Besaya", zona: "Somahoz a Cieza", km: 6, desnivel: 40, tipo: "Lineal", resumen: "Sendero pintoresco siguiendo el curso del río por su margen izquierda.", wikiloc: "https://www.wikiloc.com/hiking-trails/senda-fluvial-del-rio-besaya-tramo-somahoz-cieza-115296461" },
  { name: "El Castillo de Vispieres", comarca: "Besaya", zona: "Santillana del Mar", km: 3, desnivel: 80, tipo: "Circular", resumen: "Paseo corto a una torre medieval junto a Santillana del Mar.", wikiloc: "https://www.wikiloc.com/hiking-trails/ruta-al-castillo-de-vispieres-65672254" },
  { name: "Ruta Mitológica del Monte Tejas", comarca: "Besaya", zona: "San Felices de Buelna", km: 2, desnivel: 120, tipo: "Circular", resumen: "Sendero temático con ~50 figuras de la mitología cántabra; engancha a los peques.", wikiloc: "https://www.wikiloc.com/hiking-trails/san-felices-de-buelna-senda-mitologica-del-monte-tejas-153663714" },
  { name: "El Callejón de los Lobos", comarca: "Saja-Nansa", zona: "Cabuérniga", km: 4, desnivel: 150, tipo: "Circular", resumen: "Ruta sobre la antigua relación entre humanos y lobos, con trampa lobera (chorco).", wikiloc: "https://www.wikiloc.com/hiking-trails/eco-ruta-del-callejon-de-los-lobos-trampa-de-lobos-de-cabuerniga-175787131" },
  { name: "Vía Verde del Piquillo", comarca: "Costa Oriental", zona: "Ontón", km: 5, desnivel: 50, tipo: "Lineal", resumen: "Vía verde fácil sobre una antigua línea de tren minero, a orillas del mar. Apto carrito.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/via-verde-del-piquillo-pobena-a-onton-16618810" },
  { name: "El sendero de los porqués", comarca: "Santander", zona: "Camargo", km: 3, desnivel: 40, tipo: "Lineal", resumen: "Sendero educativo que explica la evolución del paisaje cántabro.", wikiloc: "https://www.wikiloc.com/walking-trails/el-sendero-de-los-porques-79982658" },
  { name: "Mirador del Monte Cincho", comarca: "Trasmiera", zona: "Arnuero", km: 3, desnivel: 120, tipo: "Circular", resumen: "Subida fácil a una atalaya sobre el mayor robledal de Cantabria. Ideal en familia.", wikiloc: "https://www.wikiloc.com/hiking-trails/ruta-monte-cincho-ecoparque-de-trasmiera-arnuero-13666589" },
  { name: "Ruta Accesible por la Ría de Limpias", comarca: "Asón-Agüera", zona: "Limpias", km: 3, desnivel: 10, tipo: "Lineal", resumen: "Paseo accesible junto a la ría, con parques infantiles. Apto carrito y silla de ruedas.", wikiloc: "https://www.wikiloc.com/walking-trails/ria-de-limpias-y-muelle-el-ribero-9431066" },
  { name: "El Castillo del Collado", comarca: "Santander", zona: "Camargo", km: 3, desnivel: 100, tipo: "Circular", resumen: "Pequeña ruta a un castillo altomedieval con vistas a la bahía de Santander." },
  { name: "Ruta al Refugio Número 6", comarca: "Asón-Agüera", zona: "Gibaja", km: 5, desnivel: 100, tipo: "Lineal", resumen: "Camino hasta un pueblo precioso a orillas del río Asón.", wikiloc: "https://www.wikiloc.com/walking-trails/refugio-de-pesca-n-6-gibaja-74666836" },
  { name: "Acantilados de Tagle y Torre de San Telmo", comarca: "Besaya", zona: "Suances", km: 5, desnivel: 80, tipo: "Circular", resumen: "Acantilados costeros con vistas e historia marinera.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/acantilados-de-tagle-79196807" },
  { name: "Vía Verde del Pas", comarca: "Valles Pasiegos", zona: "Valles Pasiegos", km: 6, desnivel: 40, tipo: "Lineal", resumen: "Accesible y llana, con granjas por el camino. Ideal con carrito o bici.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/via-verde-del-pas-75784553" },
  { name: "Ruta Accesible de Ramales de la Victoria", comarca: "Asón-Agüera", zona: "Ramales", km: 2, desnivel: 20, tipo: "Lineal", resumen: "Paseo fluvial corto, adaptado y accesible para todas las edades.", wikiloc: "https://es.wikiloc.com/rutas-sendero-accesible/ruta-adaptada-por-la-ribera-del-rio-ason-en-ramales-de-la-victoria-santander-11048546" },
  { name: "Ruta del Arroyo Troncos", comarca: "Campoo", zona: "Polientes (Valderredible)", km: 6, desnivel: 120, tipo: "Circular", resumen: "Sendero por el municipio más meridional de toda Cantabria.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/pueblos-matorrizos-arroyo-troncos-179169664" },
  { name: "La Canal de las Tejeras", comarca: "Besaya", zona: "Besaya", km: 5, desnivel: 150, tipo: "Lineal", resumen: "Senda fluvial poco conocida con cascadas y la ermita de San Román de Moroso.", wikiloc: "https://www.wikiloc.com/hiking-trails/cascadas-del-rio-de-la-canal-de-las-tejeras-y-ermita-de-san-roman-de-moroso-besaya-89192220" },
  { name: "Costa Quebrada por Cuchía", comarca: "Santander", zona: "Miengo", km: 4, desnivel: 50, tipo: "Lineal", resumen: "Etapa costera del parque geológico Costa Quebrada, entre playas e islotes.", wikiloc: "https://www.wikiloc.com/hiking-trails/miengo-cuchia-costa-quebrada-75018507" },
  { name: "Senda de Peñas Negras al Alto de la Gigüela", comarca: "Santander", zona: "Maoño", km: 4, desnivel: 120, tipo: "Circular", resumen: "Muy sencilla, con vistas de 360° sobre Santander y su bahía.", wikiloc: "https://www.wikiloc.com/hiking-trails/senda-de-penas-negras-alto-de-la-giguela-maono-santa-cruz-de-bezana-cantabria-23346663" },
  { name: "La Picota de Liencres", comarca: "Santander", zona: "Liencres", km: 3, desnivel: 150, tipo: "Circular", resumen: "Ascensión mítica pero muy corta, con grandes vistas sobre la costa.", wikiloc: "https://www.wikiloc.com/hiking-trails/la-picota-liencres-3776370" },
  { name: "Minas de Udías (Vía Verde de Pelurgo)", comarca: "Costa Occidental", zona: "Udías", km: 6, desnivel: 80, tipo: "Lineal", resumen: "Vía verde minera muy querida, cómoda y llana, con túneles (trae linterna).", wikiloc: "https://www.wikiloc.com/hiking-trails/minas-de-udias-80806425" },
  { name: "Los Pozos de Valcaba", comarca: "Trasmiera", zona: "Pámanes", km: 4, desnivel: 100, tipo: "Circular", resumen: "Recorrido fácil junto a dos lagunas de origen minero; refrescante en verano.", wikiloc: "https://www.wikiloc.com/hiking-trails/pr-s-26-pozos-de-valcaba-63740662" },
  { name: "Las Cascadas de Lamiña", comarca: "Saja-Nansa", zona: "Ruente", km: 3, desnivel: 80, tipo: "Lineal", resumen: "Clásico cántabro, ruta muy sencilla y segura entre cascadas.", wikiloc: "https://www.wikiloc.com/hiking-trails/valle-del-saja-nansa-valle-de-cabuernigacantabria-cascadas-de-lamina-122754401" },
  { name: "Ruta a Porcieda (pueblo abandonado)", comarca: "Liébana", zona: "Vega de Liébana", km: 5, desnivel: 250, tipo: "Lineal", resumen: "Excursión a un núcleo histórico abandonado, desde Tudes. Apta en familia.", wikiloc: "https://www.wikiloc.com/hiking-trails/visita-al-pueblo-abandonado-de-porcieda-111417694" },
  { name: "Los Pozos de Noja", comarca: "Trasmiera", zona: "Miera–Liérganes", km: 3, desnivel: 60, tipo: "Circular", resumen: "Dos lagunas entre prados, paseo tranquilo y verde con columpio gigante cerca.", wikiloc: "https://es.wikiloc.com/rutas-a-pie/127-pozos-de-noja-con-ninos-100323389" },
  { name: "Ruta de la Llasca de los Moros", comarca: "Saja-Nansa", zona: "Valdáliga", km: 4, desnivel: 100, tipo: "Circular", resumen: "Paseo desconocido a una cascada sobre una llamativa losa de piedra. Para peques.", wikiloc: "https://www.wikiloc.com/hiking-trails/la-llasca-de-los-moros-20400017" },
  { name: "Centro Geográfico de Cantabria", comarca: "Besaya", zona: "Anievas", km: 4, desnivel: 150, tipo: "Circular", resumen: "Visita curiosa al corazón geográfico exacto de la región, desde Calga.", wikiloc: "https://www.wikiloc.com/walking-trails/centro-geografico-de-cantabria-desde-calga-134784942" },
  { name: "La Casa del Monte de Ucieda", comarca: "Saja-Nansa", zona: "Ruente", km: 5, desnivel: 120, tipo: "Circular", resumen: "Ruta de los Puentes en plena reserva del Saja, entre robledales centenarios.", wikiloc: "https://www.wikiloc.com/hiking-trails/parque-natural-saja-besaya-los-puentes-de-ucieda-o-sendero-de-rozas-o-monte-rio-de-los-vados-prs-11-29536208" },
  { name: "El Churrón de Borleña", comarca: "Valles Pasiegos", zona: "Corvera de Toranzo", km: 3, desnivel: 100, tipo: "Lineal", resumen: "Cascada considerada 'la ruta para peques más bonita de Cantabria'. Corta y fácil.", wikiloc: "https://www.wikiloc.com/hiking-trails/ruta-churron-de-borlena-3131185" },
  { name: "Cueva de Cucabrera en Galizano", comarca: "Trasmiera", zona: "Ribamontán al Mar", km: 3, desnivel: 40, tipo: "Lineal", resumen: "Exploración de una cueva costera apta para familias aventureras.", wikiloc: "https://www.wikiloc.com/walking-trails/galizano-cueva-de-cucabrera-y-playa-de-galizano-35667841" },
  { name: "Senda Mitológica del Monte Hozarco", comarca: "Liébana", zona: "Peñarrubia", km: 5, desnivel: 200, tipo: "Circular", resumen: "Sendero temático con esculturas mitológicas y el mirador de Santa Catalina de premio.", wikiloc: "https://www.wikiloc.com/walking-trails/monte-hozarco-senda-mitologica-y-mirador-de-santa-catalina-penarrubia-45352737" },
  { name: "Cueva del Canónigo en Rucandio", comarca: "Trasmiera", zona: "Medio Cudeyo", km: 2, desnivel: 60, tipo: "Lineal", resumen: "Cueva 'la mejor para visitar con peques' según los locales (trae linterna).", wikiloc: "https://www.wikiloc.com/hiking-trails/cueva-del-canonigo-en-rucandio-69400497" },
  { name: "Río Saja: senda fluvial desde Carrejo", comarca: "Saja-Nansa", zona: "Cabezón de la Sal", km: 4, desnivel: 30, tipo: "Lineal", resumen: "Paseo llano y bonito junto al río Saja, con el Museo del Molino.", wikiloc: "https://www.wikiloc.com/hiking-trails/senda-fluvial-del-minchon-pr-s-120-desde-carrejo-cabezon-de-la-sal-23840217" },
  { name: "La joya escondida del río Saja (El Camarao)", comarca: "Besaya", zona: "Puente San Miguel", km: 2, desnivel: 20, tipo: "Lineal", resumen: "Paseo corto al parque de El Camarao, junto al río, con zona de baño.", wikiloc: "https://www.wikiloc.com/walking-trails/senda-fluvial-del-saja-puente-san-miguel-camarao-15319598" },
  { name: "La Fuente del Francés de Hoznayo", comarca: "Trasmiera", zona: "Entrambasaguas", km: 2, desnivel: 20, tipo: "Circular", resumen: "Entorno histórico con manantial y bosque; recorrido corto y agradable.", wikiloc: "https://www.wikiloc.com/walking-trails/fuente-del-frances-hoznayo-66931768" },
  { name: "Ruta a la Virgen de las Nieves", comarca: "Asón-Agüera", zona: "Guriezo", km: 5, desnivel: 150, tipo: "Lineal", resumen: "Escapada fácil, grande y segura, probada con peques, a una ermita sobre el valle.", wikiloc: "https://www.wikiloc.com/hiking-trails/virgen-de-las-nieves-desde-rascon-26908957" },

  // --- Nuevas ---
  { name: "Faro de Ajo (Cabo de Ajo)", comarca: "Trasmiera", zona: "Bareyo", km: 4, desnivel: 50, tipo: "Lineal", resumen: "Faro pintado por Okuda + acantilados y playa de Cuberris. Costa fácil y fotogénica.", wikiloc: "https://www.wikiloc.com/hiking-trails/paseo-faro-de-ajo-10521171" },
  { name: "Cueva de Covalanas", comarca: "Asón-Agüera", zona: "Ramales de la Victoria", km: 3, desnivel: 150, tipo: "Lineal", resumen: "Cueva con arte rupestre (Patrimonio Mundial). Subida corta por bosque hasta la cueva.", wikiloc: "https://www.wikiloc.com/hiking-trails/cueva-de-covalanas-desde-ramales-de-la-victoria-27897459" },
  { name: "Rías de Tina Menor", comarca: "Costa Occidental", zona: "Pechón (Val de San Vicente)", km: 4, desnivel: 80, tipo: "Lineal", resumen: "Miradores sobre la ría del Nansa y la antigua torre de avistamiento de ballenas.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/mirador-de-tina-menor-y-mirador-de-torre-rudi-pechon-76784188" },
  { name: "Embalse de Alsa", comarca: "Besaya", zona: "Arenas de Iguña", km: 6, desnivel: 50, tipo: "Circular", resumen: "Vuelta llana a un embalse tranquilo entre prados; agua, patos y mucha calma.", wikiloc: "https://www.wikiloc.com/hiking-trails/circular-embalse-de-alsa-9827012" },
  { name: "Senda Fluvial del Río Miera", comarca: "Trasmiera", zona: "Rubalcaba (Liérganes)", km: 4, desnivel: 40, tipo: "Lineal", resumen: "Sencillo y precioso paseo fluvial con praderas y pozas para refrescarse en verano.", wikiloc: "https://www.wikiloc.com/hiking-trails/sencillo-y-precioso-paseo-por-el-senda-fluvial-del-rio-miera-praderas-de-brenaescobal-y-huyoceda-ha-126429228" },
  { name: "Parque de Mataleñas", comarca: "Santander", zona: "Santander", km: 3, desnivel: 30, tipo: "Circular", resumen: "Parque costero sobre el mar con el faro de Cabo Menor. Apto carrito.", wikiloc: "https://www.wikiloc.com/walking-trails/circular-parque-de-matalenas-santander-120351608" },
  { name: "Senda Mitológica La Cava (Sámano)", comarca: "Costa Oriental", zona: "Castro Urdiales", km: 1.5, desnivel: 20, tipo: "Lineal", resumen: "Mini senda con 11 figuras mitológicas; llana y perfecta para los más peques.", wikiloc: "https://www.wikiloc.com/walking-trails/senda-mitologica-la-cava-valle-de-samano-castro-urdiales-cantabria-221575442" },
  { name: "Faro de Suances", comarca: "Besaya", zona: "Suances", km: 4, desnivel: 60, tipo: "Circular", resumen: "Acantilados, faro y la espectacular Playa de los Locos.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/circular-desde-faro-suances-2023-149084526" },
  { name: "Cuevas del Monte Castillo", comarca: "Besaya", zona: "Puente Viesgo", km: 4, desnivel: 150, tipo: "Circular", resumen: "Cuevas con arte rupestre de las más antiguas del mundo + sendero fluvial.", wikiloc: "https://www.wikiloc.com/hiking-trails/puente-viesgo-cuevas-del-monte-castillo-11289766" },
  { name: "El Puntal de Somo y dunas de Loredo", comarca: "Trasmiera", zona: "Ribamontán al Mar", km: 5, desnivel: 20, tipo: "Lineal", resumen: "Dunas, pinar de Arna y kilómetros de playa frente a Santander.", wikiloc: "https://es.wikiloc.com/rutas-senderismo/el-puntal-somo-dunas-de-loredo-pinar-de-arna-8590722" },
  { name: "Playa de Berria (Santoña)", comarca: "Trasmiera", zona: "Santoña", km: 4, desnivel: 20, tipo: "Lineal", resumen: "Paseo marítimo llano entre marismas, dunas y la gran playa de Berria.", wikiloc: "https://www.wikiloc.com/hiking-trails/paseo-maritimo-de-santona-argonos-playa-de-berria-santona-30899793" },
  { name: "Comillas (Capricho de Gaudí y playa)", comarca: "Costa Occidental", zona: "Comillas", km: 4, desnivel: 50, tipo: "Circular", resumen: "Paseo por el pueblo: Capricho de Gaudí, Sobrellano, miradores y playa.", wikiloc: "https://www.wikiloc.com/hiking-trails/comillas-palacio-de-sobrellano-capricho-de-gaudi-universidad-pontificia-iglesia-de-san-cristobal-79256957" },
]

export const comarcas = [...new Set(routes.map(r => r.comarca))].sort()

function mapsQuery(r) {
  return encodeURIComponent(`${r.name}, ${r.zona}, Cantabria, España`)
}
export function mapsDirectionsUrl(r) {
  return `https://www.google.com/maps/dir/?api=1&destination=${mapsQuery(r)}`
}
export function wikilocUrl(r) {
  if (r.wikiloc) return r.wikiloc
  const limpio = r.name
    .replace(/\s*\([^)]*\)/g, "")
    .replace(/^(Ruta|Sendero|Senda|Paseo|Subida)\s+(a|al|de|del|por|por la)\s+/i, "")
    .trim()
  return `https://www.google.com/search?q=${encodeURIComponent("site:wikiloc.com " + limpio + " Cantabria")}`
}
